### ISSUE TITLE
OpenLibrary support (prototype)

### ISSUE THREAD

**Issue by jacobandresen** [solsort/bogapp#2]
Explore how to support searching and downloading e-books from OpenLibrary.

**Comment by jacobandresen** [comment]
https://openlibrary.org/developers/api

Nice cover api

**Comment by rasmuserik** [comment]
Maybe it would make sense to start with openlibrary initially, and then add openplatform later.

From what I have seen, I really like the approach of openlibrary, so I suggest we try to follow their data model, etc.

**Comment by jacobandresen** [comment]
Any thoughts on how we should go about abstracting calls to the library systems? Right now I have a "search" function inside api.js  in #4 . This works for one system , I suppose. But if we are to have several, how should we approach it? Some kind of driver system , perhaps?

**Comment by rasmuserik** [comment]
After looking into openlibrary yesterday, I am actually thinking about changing the approach quite a bit.

Are you on riot.im? It is probably easier to chat about it there.

**Comment by rasmuserik** [comment]
I created a room: https://riot.im/app/#/room/#mobibl:matrix.org
which I think would be useful for using for the project in general.

(riot is instant messaging, a la irc/slack/..., but more open/distributed/...)

**Comment by jacobandresen** [comment]
Starting out with trying to search via Openlibrary in #4  . Let's make a separate issue for viewing/downloading books if needed.
