### ISSUE TITLE
More info - Cover photo lookup

### ISSUE THREAD

**Issue by jacobandresen** [solsort/bogapp#3]
Take a picture of the book cover. Use this to find more information about the book via BogApp.

**Comment by jacobandresen** [comment]
@rasmuserik will it cause legal issues if the users provide a photo of an actual book? Will it infringe on anyones copyright?

**Comment by rasmuserik** [comment]
@jacobandresen I don't know.

Have you looked into / experimented with looking up books by cover?

This could be super nice :)

**Comment by jacobandresen** [comment]
looking into it now.  it should be doable to recognize ISBN style numbers from the client. Maybe even the title?

**Comment by jacobandresen** [comment]
Looks like @aklt  is doing this in #5  ;)

**Comment by rasmuserik** [comment]
closing this issue, as #5 seems to have the same functionality, and @aklt is working on it
